lint:
  files_unchanged:
  - assets/nf-core-pairgenomealign_logo_light.png
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: charles-plessy
  description: Pairwise alignment pipeline (genome to genome or reads to genome)
  force: false
  is_nfcore: true
  name: pairgenomealign
  org: nf-core
  outdir: .
  version: 2.2.1dev
