lint:
nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: charles-plessy
  description: Pairwise alignment pipeline (genome to genome or reads to genome)
  force: false
  is_nfcore: true
  name: pairgenomealign
  org: nf-core
  outdir: .
  version: 1.1.1
