name: pairalign_m2o
description: |
  Performs many-to-one pairwise genome alignment using LAST and generates alignment views (M2O, O2O).
  This subworkflow indexes the target genome, trains alignment parameters, performs direct many-to-one alignment
  using specific parameter modules, and derives one-to-one alignment through split operation.
  Optionally generates dotplots for each alignment type with filtering options.
keywords:
  - alignment
  - genomics
  - LAST
  - pairwise alignment
  - many-to-one
  - dotplot
components:
  - last/lastdb
  - last/train
  - last/lastal
  - last/split
  - last/dotplot
input:
  - ch_target:
      type: channel
      description: |
        Channel containing the target genome file
        Structure: [meta, fasta]
  - ch_queries:
      type: channel
      description: |
        Channel containing query genome sequences from samplesheet
        Structure: [meta, fasta]
  - ch_target_bed:
      type: channel
      description: |
        Channel containing BED file with positions of poly-N stretches in target genome
        Structure: [meta, bed]
  - ch_queries_bed:
      type: channel
      description: |
        Channel containing BED files with positions of poly-N stretches in query genomes
        Structure: [meta, bed]
output:
  - multiqc:
      type: channel
      description: |
        Channel containing MultiQC compatible files from training and split operations
        Structure: [file]
  - m2o:
      type: channel
      description: |
        Channel containing many-to-one alignment in MAF format
        Structure: [meta, maf]
  - o2o:
      type: channel
      description: |
        Channel containing one-to-one alignment in MAF format
        Structure: [meta, maf]
authors:
  - "@nf-core/pairgenomealign"
maintainers:
  - "@nf-core/pairgenomealign"